CREATE TABLE restaurants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    street VARCHAR(160) NOT NULL,
    city VARCHAR(100) NOT NULL
);

CREATE TABLE menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    price NUMERIC(10, 2) NOT NULL,
    category VARCHAR(60) NOT NULL,
    available BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_menu_item_restaurant
        FOREIGN KEY (restaurant_id)
        REFERENCES restaurants(id)
        ON DELETE CASCADE,

    CONSTRAINT uq_menu_item_name_per_restaurant
        UNIQUE (restaurant_id, name),

    CONSTRAINT check_menu_item_price
        CHECK (price >= 0)
);
